default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: YOUR_USERNAME_MYSQL
  password: 'YOUR_PASSWORD_MYSQL'
  socket: /var/run/mysqld/mysqld.sock
  encoding: utf8mb4
  collate: utf8mb4_unicode_ci

development:
  <<: *default
  database: mekari_project_development
